language: rust
sudo: required
#sudo: false # get this back when radare2 source is removed
matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

addons: #all of the addons are for r2 get rid of them
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - dc
      - binutils
      - cabextract
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - jq
      - gcc-4.8
      - g++-4.8

install:
  - git clone https://github.com/radare/radare2.git
  - cd radare2
  - sys/install.sh
  - export PKG_CONFIG_PATH=${TRAVIS_BUILD_DIR}/pkgcfg:${PKG_CONFIG_PATH}
  - export PATH=${TRAVIS_BUILD_DIR}/install/bin:${PATH}
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/install/lib:${LD_LIBRARY_PATH}
  - cd ../
  - cargo build --release --verbose
script:
  - cd test
  - for f in *.sh; do bash "$f"; done
  - cd ../r_search
  - cargo test --verbose
notifications:
  email:
    on_success: never
