[workspace]
members = [
  "rio",
  "rtrees",
  "test_file",
]
[package]
name = "rcore"
version = "0.1.0"
authors = ["oddcoder <ahmedsoliman@oddcoder.com>"]
license = "LGPL"
repository = "https://github.com/oddcoder/rair"
keywords = ["Rair", "Core"]
description = "Core module for Rair"
categories = ["CLI"]
readme = "readme.md"



[dependencies]
yansi = "0.5"

rio = {path = "rio"}
rtrees = {path = "rtrees"}
serde = { version = "1.0", features = ["derive"]}
serde_cbor = "0.10"
flate2 = "1.0"
[dev-dependencies]

test_file = {path = "test_file"}
